module.exports = {
  roots: ['<rootDir>/src'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
  testMatch: ['<rootDir>/src/**/*.spec.ts'],
  testPathIgnorePatterns: ['dist'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  testEnvironment: 'node',
  maxWorkers: 4,
  verbose: true,
  collectCoverage: true,
  detectOpenHandles: true,
  passWithNoTests: true,
  forceExit: true,
  coveragePathIgnorePatterns: ['<rootDir>/(sdks|__fixtures__|__tests__)/', '<rootDir>/src/sdks'],
  collectCoverageFrom: [
    '<rootDir>/src/**/*.{js,ts,tsx}',
    '!<rootDir>/src/main.ts',
    '!<rootDir>/src/repl.ts',
    '!<rootDir>/src/config/*',
    '!<rootDir>/src/**/index.ts',
    '!<rootDir>/src/**/*.spec.ts',
    '!<rootDir>/src/**/*.*-spec.ts',
    '!<rootDir>/src/**/__tests__/**/*',
    '!<rootDir>/src/**/__fixtures__/**/*',
    '!<rootDir>/src/**/(dto|interfaces|entities)/*',
    '!<rootDir>/src/**/*.(module|dto|interface|interfaces|enum|entity).ts',
    '!<rootDir>/src/app.(factory|metadata|module|graphql|swagger|constants).ts',
  ],
  coverageReporters: ['html', 'lcov', 'text', 'text-summary'],
  coverageThreshold: {
    global: {
      statements: 0,
      branches: 0,
      lines: 0,
      functions: 0,
    },
  },
};
